=== MahdiSaber/E-PIX/epix-project/epix-de/src/main/resources/matching-config-2.1.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by Christian Schack (UniversitÃ¤tsklinikum Greifswald) -->
<xs:schema xmlns:ma="http://www.ganimed.icmvc.emau.org/deduplication/config/model" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ganimed.icmvc.emau.org/deduplication/config/model" elementFormDefault="unqualified" version="1.0">
	<xs:element name="MatchingConfiguration" type="ma:MatchingConfiguration"/>
	<xs:complexType name="SimpleType">
		<xs:sequence>
			<xs:element name="property-type" type="xs:string"/>
			<xs:element name="regex-pattern" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="threshold-config" type="ma:ThresholdConfiguration"/>
			<xs:element name="algorithm" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ObjectField">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:choice>
				<xs:element name="simple-type" type="ma:SimpleType"/>
				<xs:element name="complex-type" type="ma:ObjectType"/>
				<xs:element name="list-type" type="ma:ObjectType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ObjectType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="object-field" type="ma:ObjectField" minOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="qualified-class-name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="ObjectOfSingleTruth">
		<xs:sequence>
			<xs:element name="global-threshold" type="ma:ThresholdConfiguration"/>
			<xs:element name="object-type" type="ma:ObjectType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MatchingConfiguration">
		<xs:sequence>
			<xs:element name="version" type="xs:string"/>
			<xs:element name="safe-system-oid" type="xs:string"/>
			<xs:element name="pageSize" type="xs:int"/>
			<xs:element name="report-file" type="xs:string"/>
			<xs:element name="deduplication-algorithm" type="xs:string"/>
			<xs:element name="preprocessing-config" type="ma:PreprocessingConfig" minOccurs="0"/>
			<xs:element name="required-config" type="ma:RequiredConfig" minOccurs="0"/>
			<xs:element name="object-of-single-truth" type="ma:ObjectOfSingleTruth"/>
			<xs:element name="blocking" type="ma:Blocking"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ThresholdConfiguration">
		<xs:sequence>
			<xs:element name="threshold" type="xs:double"/>
			<xs:element name="reject-threshold" type="xs:double" minOccurs="0"/>
			<xs:element name="weight" type="xs:double" default="1.0" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PreprocessingConfig">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="preprocessing-type" type="ma:PreprocessingType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PreprocessingType">
		<xs:sequence>
			<xs:element name="preprocessing-field" type="ma:PreprocessingField" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="qualified-class-name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="PreprocessingField">
		<xs:sequence>
			<xs:element name="field-name" type="xs:string"/>
			<xs:choice>
				<xs:element name="simple-transformation-type" type="ma:Transformation" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="complex-transformation-type" type="ma:PreprocessingType"/>
				<xs:element name="list-transformation-type" type="ma:PreprocessingType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Transformation">
		<xs:sequence>
			<xs:element name="description" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ComplexTransformation" mixed="false">
		<xs:complexContent mixed="false">
			<xs:extension base="ma:Transformation">
				<xs:sequence>
					<xs:element name="qualified-class-name" type="xs:string"/>
					<xs:element name="transformation-method" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Blocking">
		<xs:sequence>
			<xs:element name="blocking-threshold" type="ma:ThresholdConfiguration"/>
			<xs:element name="blocking-type" type="ma:ObjectType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SimpleTransformation" mixed="false">
		<xs:complexContent mixed="false">
			<xs:extension base="ma:Transformation">
				<xs:sequence>
					<xs:element name="input-pattern" type="xs:string" default=""/>
					<xs:element name="output-pattern" type="xs:string" default=""/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RequiredConfig">
	<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="required-type" type="ma:RequiredType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
		<xs:complexType name="RequiredType">
		<xs:sequence>
			<xs:element name="qualified-class-name" type="xs:string"/>
			<xs:element name="required-field" type="ma:RequiredField" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>	
	<xs:complexType name="RequiredField">
		<xs:sequence>
			<xs:element name="field-name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== MahdiSaber/E-PIX/source/epix-project/epix-core/src/main/resources/matching-config-2.2.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ###license-information-start###
  E-PIX - Enterprise Patient Identifier Cross-referencing
  __
  Copyright (C) 2009 - 2017 The MOSAIC Project - Institut fuer Community Medicine der
  							Universitaetsmedizin Greifswald - mosaic-projekt@uni-greifswald.de
  							concept and implementation
  							c. schack, d.langner, l. geidel
  							web client
  							a. blumentritt
  							g. weiher
  							please cite our publications
  							http://dx.doi.org/10.3414/ME14-01-0133
  							http://dx.doi.org/10.1186/s12967-015-0545-6
  __
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  ###license-information-end###
  -->

<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by Christian Schack 
	(UniversitÃ¤tsklinikum Greifswald) -->
<ma:MatchingConfiguration
	xmlns:ma="http://www.ganimed.icmvc.emau.org/deduplication/config/model"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	
	xsi:schemaLocation="http://www.ganimed.icmvc.emau.org/deduplication/config/model matching-config-2.1.0.xsd ">
	<version>1.0.0</version>
	<safe-system-oid>1.2.276.0.76.3.1.132.100.1.1.1.3.0.1.1</safe-system-oid>
	<pageSize>10000</pageSize>
	<report-file></report-file>
	<deduplication-algorithm>org.emau.icmvc.ganimed.deduplication.impl.FellegiSunterAlgorithm</deduplication-algorithm>

	<required-config>
		<required-type>
			<qualified-class-name>org.emau.icmvc.ganimed.epix.core.persistence.model.PatientPreprocessed</qualified-class-name>
			<required-field>
				<field-name>firstName</field-name>
			</required-field>
			<required-field>
				<field-name>lastName</field-name>
			</required-field>
			<required-field>
				<field-name>birthDate</field-name>
			</required-field>
			<required-field>
				<field-name>gender</field-name>
			</required-field>
		</required-type>
		<required-type>
			<qualified-class-name>org.emau.icmvc.ganimed.epix.core.persistence.model.HealthcareProviderPreprocessed</qualified-class-name>
			<required-field>
				<field-name>firstName</field-name>
			</required-field>
			<required-field>
				<field-name>lastName</field-name>
			</required-field>
			<required-field>
				<field-name>birthDate</field-name>
			</required-field>
			<required-field>
				<field-name>gender</field-name>
			</required-field>
		</required-type>
	</required-config>
	<preprocessing-config>
		<preprocessing-type qualified-class-name="org.emau.icmvc.ganimed.epix.core.persistence.model.PersonPreprocessed">
			<preprocessing-field required="true">
				<field-name>firstName</field-name>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>Â?</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>?</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>Ã©</input-pattern>
						<output-pattern>e</output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>Dr.</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>Prof.</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern> med.</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>rer.</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>nat.</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>Ing.</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>Dipl.</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>,</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern> </input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:SimpleTransformation">
						<input-pattern>-</input-pattern>
						<output-pattern></output-pattern>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:ComplexTransformation">
						<qualified-class-name>org.emau.icmvc.ganimed.deduplication.preprocessing.impl.ToUpperCaseTransformation</qualified-class-name>
						<transformation-method>transform</transformation-method>
					</simple-transformation-type>
					<simple-transformation-type xsi:type="ma:ComplexTransformation">
						<qualified-class-name>org.emau.icmvc.ganimed.deduplication.preprocessing.impl.CharsMutationTransformation</qualified-class-name>
						<transformation-method>transform</transformation-method>
					</simple-transformation-type>
			</preprocessing-field>
			<preprocessing-field>
				<field-name>middleName</field-name>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern> </input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>-</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:ComplexTransformation">
					<qualified-class-name>org.emau.icmvc.ganimed.deduplication.preprocessing.impl.ToUpperCaseTransformation</qualified-class-name>
					<transformation-method>transform</transformation-method>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:ComplexTransformation">
					<qualified-class-name>org.emau.icmvc.ganimed.deduplication.preprocessing.impl.CharsMutationTransformation</qualified-class-name>
					<transformation-method>transform</transformation-method>
				</simple-transformation-type>
			</preprocessing-field>
			<preprocessing-field>
				<field-name>lastName</field-name>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>Â?</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>?</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>Ã©</input-pattern>
					<output-pattern>e</output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>Dr.</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>Prof.</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>med.</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>rer.</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>nat.</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>Ing.</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>Dipl.</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>,</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern> </input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:SimpleTransformation">
					<input-pattern>-</input-pattern>
					<output-pattern></output-pattern>
				</simple-transformation-type>
				<simple-transformation-type xsi:type="ma:ComplexTransformation">
					<qualified-class-name>org.emau.icmvc.ganimed.deduplication.preprocessing.impl.ToUpperCaseTransformation</qualified-class-name>
					<transformation-method>transform</transformation-method>
				</simple-transformation-type>
